x-app-base: &app_base
  build: .
  volumes:
    - "./:/app"
    - "/app/node_modules"
  env_file:
    - ".env.development"
  environment:
    - DATABASE_URL=postgresql://postgres:dummy@db:5433
    - SMTP_ADDRESS=mailcatcher
  depends_on:
    - db
    - mailcatcher

services:
  web:
    <<: *app_base
    ports:
      - "3000:3000"
      - "12345:12345"
  worker:
    <<: *app_base
    command: bundle exec good_job start --queues=critical,default;low
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 'dummy'
      PGPORT: 5433
    ports:
      - "5433:5433"
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP Server
