services:
  web:
    build: .
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
      - "12345:12345"
    env_file:
       - '.env.development'
    environment:
      - DATABASE_URL=postgresql://postgres:dummy@db:5433
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 'dummy'
      PGPORT: 5433
    ports:
      - "5433:5433"
