---
openapi: 3.0.1
info:
  title: Mon Devis Sans Oublis API V1
  version: v1
  description: |
    **Général champs:**
    - les champs optionnels sont nullables voir peuvent ne pas être présents dans le payload
    - `id` : considérer comme un string unique
    - type enum : comme des strings
paths:
  "/profiles":
    get:
      summary: Récupérer les profils disponibles
      tags:
      - Profils
      responses:
        '200':
          description: liste des profiles
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    data:
                      type: "#/components/schemas/profile"
                required:
                - data
  "/quote_checks/{quote_check_id}/feedbacks":
    post:
      summary: Déposer un retour global ou sur error detail
      tags:
      - Devis
      security:
      - basic_auth: []
      parameters:
      - name: quote_check_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Retour téléversé
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/quote_check_feedback"
        '422':
          description: missing params
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/api_error"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
                properties:
                  rating:
                    type: integer
                    nullable: false
                    description: de 0 à 5 (trés satisfait) inclus
                  email:
                    type: string
                    nullable: true
                  comment:
                    type: string
                    nullable: true
                    maxLength: 1000
                required:
                - rating
              - type: object
                properties:
                  validation_error_details_id:
                    type: string
                    nullable: false
                  is_helpful:
                    type: boolean
                    nullable: false
                  comment:
                    type: string
                    nullable: true
                    maxLength: 1000
                required:
                - validation_error_details_id
                - is_helpful
  "/quote_checks/{quote_check_id}/error_details/{error_details_id}/feedbacks":
    post:
      summary: Déposer un retour
      tags:
      - Devis
      security:
      - basic_auth: []
      parameters:
      - name: quote_check_id
        in: path
        required: true
        schema:
          type: string
      - name: error_details_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Retour téléversé
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/quote_check_feedback"
        '422':
          description: missing params
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/api_error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                is_helpful:
                  type: boolean
                  nullable: false
                comment:
                  type: string
                  nullable: true
                  maxLength: 1000
              required:
              - is_helpful
  "/quote_checks":
    post:
      summary: Téléverser un devis
      tags:
      - Devis
      security:
      - basic_auth: []
      parameters: []
      description: Au retour le devis a été téléversé avec succès.<br>Mais vérifiez
        selon le statut si le devis a été déjà analysé ou non.<br>Il peut contenir
        des erreurs dès le téléversement.<br>Si le statut est 'pending', cela signifie
        que l'analyse est encore en cours.<br>Et qu'il faut boucler sur l'appel /quote_check/:id
        pour récupérer le devis à jour.
      responses:
        '201':
          description: Devis téléversé
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/quote_check"
        '422':
          description: invalid request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/api_error"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                profile:
                  "$ref": "#/components/schemas/profile"
                parent_id:
                  type: string
                  nullable: true
              required:
              - file
              - profile
  "/quote_checks/{id}":
    get:
      summary: Récupérer un Devis
      tags:
      - Devis
      security:
      - basic_auth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Devis trouvé
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/quote_check"
        '404':
          description: Devis non trouvé
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/api_error"
  "/stats":
    get:
      summary: Récupérer les stats
      tags:
      - Stats
      responses:
        '200':
          description: liste des stats
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/stats"
produces:
- application/json
consumes:
- application/json
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
  schemas:
    api_error:
      type: object
      properties:
        error:
          type: string
        message:
          type: array
          items:
            type: string
    profile:
      type: string
      enum:
      - artisan
      - particulier
      - mandataire
      - conseiller
    quote_check_status:
      type: string
      enum:
      - pending
      - valid
      - invalid
      description: 'pending: analyse en cours | valid: valide | invalid: invalide'
    quote_check_error_category:
      type: string
      enum:
      - admin
      - file
      - gestes
      description: 'admin: Mentions administratives | file: Fichier | gestes: Descriptif
        technique des gestes'
    quote_check_error_code:
      type: string
      description: code d'erreur
    quote_check_error_type:
      type: string
      enum:
      - missing
      - wrong
      description: 'missing: Information manquante | wrong: Information erronée'
    quote_check_error_details:
      type: object
      properties:
        id:
          type: string
          description: UUID unique
        category:
          "$ref": "#/components/schemas/quote_check_error_category"
        type:
          "$ref": "#/components/schemas/quote_check_error_type"
        code:
          "$ref": "#/components/schemas/quote_check_error_code"
        title:
          type: string
        problem:
          type: string
          description: Réutilisez le title si vide
        solution:
          type: string
          description: peut-être vide
        provided_value:
          type: string
          description: peut-être vide, ou ligne du geste correspondant
        value:
          type: string
          description: DEPRECATED
      required:
      - id
      - code
    quote_check:
      type: object
      properties:
        id:
          type: string
          description: UUID unique
        parent_id:
          type: string
          nullable: true
        status:
          "$ref": "#/components/schemas/quote_check_status"
        profile:
          "$ref": "#/components/schemas/profile"
        valid:
          type: boolean
          nullable: true
        errors:
          type: array
          items:
            "$ref": "#/components/schemas/quote_check_error_code"
          description: liste des erreurs dans ordre à afficher
          nullable: true
        error_details:
          type: array
          items:
            "$ref": "#/components/schemas/quote_check_error_details"
          description: liste des erreurs avec détails dans ordre à afficher
          nullable: true
        error_messages:
          type: object
          additionalProperties:
            type: string
            description: code d'erreur => message
          nullable: true
      required:
      - id
      - status
      - profile
    quote_check_feedback:
      type: object
      properties:
        id:
          type: string
          description: UUID unique
        quote_check_id:
          type: string
          nullable: false
        validation_error_details_id:
          type: string
          nullable: true
          description: requis pour feedback error detail
        is_helpful:
          type: boolean
          nullable: true
          description: requis pour feedback error detail
        rating:
          type: integer
          nullable: true
          description: requis pour feedback global hors error detail
        comment:
          type: string
          nullable: true
          maxLength: 1000
      required:
      - quote_check_id
    stats:
      type: object
      properties:
        quote_checks_count:
          type: integer
        average_quote_check_errors_count:
          type: number
          description: nombre moyen d'erreurs par analyse
          nullable: true
        average_quote_check_cost:
          type: number
          description: coût moyen d'une analyse en Euro (€)
          nullable: true
        unique_visitors_count:
          type: integer
          description: nombre de visiteurs uniques dans le temps
          nullable: true
      required:
      - quote_checks_count
      - average_quote_check_errors_count
      - average_quote_check_cost
      - unique_visitors_count
servers:
- url: https://api.staging.mon-devis-sans-oublis.beta.gouv.fr/api/v1
  description: Staging server
- url: https://api.mon-devis-sans-oublis.beta.gouv.fr/api/v1
  description: Production server
- url: http://localhost:3000/api/v1
  description: Development server
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
