
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test
  username: postgres 
  password: dummy 
  host: db 
  port: 5433

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
