default: &default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/2") %>
  
production:
  url: <%= ENV.fetch("REDIS_URL") %>
  ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
