name: Build

on:
    workflow_call:
    workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
        with: docker
      - uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            BUNDLE_WITHOUT=development production
          tags: rails-template:latest
          outputs: type=docker,dest=/tmp/rails-template.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Cache image
        id: rails-template-docker
        uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
