name: Fiability tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ALBERT_MODEL: ${{ vars.ALBERT_MODEL || 'meta-llama/Llama-3.1-8B-Instruct' }}
  DATABASE_URL: postgres://postgres:dummy@localhost:5432/test
  FIABILITY_THRESHOLD: ${{ vars.FIABILITY_THRESHOLD || '0.6' }}
  MISTRAL_MODEL: ${{ vars.MISTRAL_MODEL || 'mistral-large-latest' }}

jobs:
  build:
    uses: ./.github/workflows/build.yaml
  fiability:
    name: "Fiability tests"
    runs-on: ubuntu-latest
    needs: build
    environment: production
    services:
      postgres:
        # TODO: Fix reuse of POSTGRES_VERSION
        # image: "postgres:${{ env.POSTGRES_VERSION }}"
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: dummy
          POSTGRES_VERSION: "16"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - env:
          ALBERT_API_KEY: ${{ secrets.ALBERT_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          TEST_SOURCE_DATABASE_URL: ${{ secrets.TEST_SOURCE_DATABASE_URL }}
        run: |
          docker run \
            --network="host" \
            -e ALBERT_MODEL="${{ env.ALBERT_MODEL }}" \
            -e ALBERT_API_KEY="${{ env.ALBERT_API_KEY }}" \
            -e DATABASE_URL="${{ env.DATABASE_URL }}" \
            -e FIABILITY_THRESHOLD="${{ env.FIABILITY_THRESHOLD }}" \
            -e MISTRAL_MODEL="${{ env.MISTRAL_MODEL }}" \
            -e MISTRAL_API_KEY="${{ env.MISTRAL_API_KEY }}" \
            -e TEST_SOURCE_DATABASE_URL="${{ env.TEST_SOURCE_DATABASE_URL }}" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --rm rails-template bash -c "bin/rails db:environment:set RAILS_ENV=test && bundle exec rake quote_checks:fiability" | tee logs/fiability_test_results.txt
          if grep -q "❌ FAILED" logs/fiability_test_results.txt; then
            exit 1
          fi
      - name: Upload Fiability Test Results
        uses: actions/upload-artifact@v4
        with:
          name: fiability-test-results
          path: logs/fiability_test_results.txt
