name: "Run Fiability tests"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/test.yaml
  fiability:
    name: "Fiability tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Fiability tests
        env:
          TEST_SOURCE_DATABASE_URL: ${{ secrets.TEST_SOURCE_DATABASE_URL }}
        run: bundle exec rake quote_checks:fiability
