name: Fiability tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/test.yaml
  fiability:
    name: "Fiability tests"
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        # TODO: Fix reuse of POSTGRES_VERSION
        # image: "postgres:${{ env.POSTGRES_VERSION }}"
        image: postgres:16
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: dummy
          POSTGRES_VERSION: "16"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/rails-template.tar
          key: ${{ github.sha }}-rails-template
      - run: docker load --input /tmp/rails-template.tar
      - env:
          TEST_SOURCE_DATABASE_URL: ${{ secrets.TEST_SOURCE_DATABASE_URL }}
        run: |
          docker run \
            --network="host" \
            -e DATABASE_URL="${{ env.DATABASE_URL }}" \
            -e TEST_SOURCE_DATABASE_URL="${{ env.TEST_SOURCE_DATABASE_URL }}" \
            -v /var/run/docker.sock:/var/run/docker.sock \
            --rm rails-template bundle exec rspec
